### ISSUE TITLE
Black map after resume on Android

### ISSUE THREAD

**Issue by artemsorochan** [mapbox/mapbox-maps-flutter#205] opened 2023-07-12 06:53 UTC
Map becomes black when resumes the app on Android. It doesn't happen on all devices. Sometimes it flickers for 1 second, sometimes stay longer or even forever until app restart. We didn't find any relations to the code, therefore can't provide any reproducable code. Any suggestion would be helpful. We use PointAnnotationManager, PolylineAnnotationManager, PolygonAnnotationManager, OnPointAnnotationClickListener

mapbox_maps_flutter: 0.4.4
 Flutter (Channel stable, 3.10.3)

**Comment by T-moz** [comment] 2023-11-10 18:31
I also faced this issues.

The problem is also present with https://github.com/maplibre/flutter-maplibre-gl

**Comment by evil159** [comment] 2024-04-12 10:03
Hi all, this issue should be fixed in https://github.com/mapbox/mapbox-maps-flutter/pull/391, feel free to reopen this ticket if you have any feedback!

**Closed by evil159** 2024-04-12 10:03 UTC
