### ISSUE TITLE
Always get exception "java.lang.Throwable: Source line_source_view_info is not in style"

### ISSUE THREAD

**Issue by ggever** [mapbox/mapbox-maps-flutter#40] opened 2023-01-14 21:51 UTC
Hello.
I got some problems. So I want to share it.
I have 2 screens. They are both using MapWidget. In 1st screen, I created a line layer and source [line_source_view_info] for that layer. It worked.
When I go to the 2nd screen, it throwed this exception "java.lang.Throwable: Source line_source_view_info is not in style". I think that source data is not removed/disposed in the right way.
So could you please take a look. Thank you

**Comment by AAverin1994** [comment] 2023-02-09 09:49
I have got the same problem when I try to use function getSource. 

Before that I have created the GeoJsonSource and add it using addSource function. After that I tried to get created source using created source id and get the same error.

**Comment by AAverin1994** [comment] 2023-02-09 09:51
@sbma44 @RennanAgroSmart @yunikkk @LjubiTech-Maxko Could you please help us with it? It is very important for me.

**Comment by LjubiTech-Maxko** [comment] 2023-02-09 09:58
Could you first try to use the main branch of the git repository as a dependency for maps and check if the error still exists.

```yaml
  mapbox_maps_flutter:
    git:
      url: https://github.com/mapbox/mapbox-maps-flutter
      ref: main
```

I think this should be resolved with recent updates for multimap fix, but new version still isn't published to pub.dev. If that doesn't work could you please add the minimal reproduction code sample?

**Comment by AAverin1994** [comment] 2023-02-09 11:59
> Could you first try to use the main branch of the git repository as a dependency for maps and check if the error still exists.
> 
> ```yaml
>   mapbox_maps_flutter:
>     git:
>       url: https://github.com/mapbox/mapbox-maps-flutter
>       ref: main
> ```
> 
> I think this should be resolved with recent updates for multimap fix, but new version still isn't published to pub.dev. If that doesn't work could you please add the minimal reproduction code sample?

@LjubiTech-Maxko thank you for your answer. I have tried to do it, but I got this error:

```
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - Flutter
      - airship_flutter
      - app_settings
      - flutter_inappwebview
      - flutter_secure_storage
      - location
      - mapbox_maps_flutter
      - mobile_scanner
      - path_provider_ios
      - permission_handler_apple
      - share_plus
      - shared_preferences_ios
      - url_launcher_ios

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `airship_flutter` from `.symlinks/plugins/airship_flutter/ios`
    -> Fetching podspec for `app_settings` from `.symlinks/plugins/app_settings/ios`
    -> Fetching podspec for `flutter_inappwebview` from `.symlinks/plugins/flutter_inappwebview/ios`
    -> Fetching podspec for `flutter_secure_storage` from `.symlinks/plugins/flutter_secure_storage/ios`
    -> Fetching podspec for `location` from `.symlinks/plugins/location/ios`
    -> Fetching podspec for `mapbox_maps_flutter` from `.symlinks/plugins/mapbox_maps_flutter/ios`
    -> Fetching podspec for `mobile_scanner` from `.symlinks/plugins/mobile_scanner/ios`
    -> Fetching podspec for `path_provider_ios` from `.symlinks/plugins/path_provider_ios/ios`
    -> Fetching podspec for `permission_handler_apple` from `.symlinks/plugins/permission_handler_apple/ios`
    -> Fetching podspec for `share_plus` from `.symlinks/plugins/share_plus/ios`
    -> Fetching podspec for `shared_preferences_ios` from `.symlinks/plugins/shared_preferences_ios/ios`
    -> Fetching podspec for `url_launcher_ios` from `.symlinks/plugins/url_launcher_ios/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_d_e_7.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/d/e/7/Airship/16.10.7/Airship.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/d/e/7/Airship/16.9.4/Airship.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/d/e/7/Airship/16.9.4/Airship.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/d/e/7/Airship/16.9.4/Airship.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/d/e/7/Airship/16.9.4/Airship.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_6_8_6.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/6/8/6/OrderedSet/5.0.0/OrderedSet.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_b_e_b.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/b/e/b/GoogleMLKit/3.2.0/GoogleMLKit.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/b/e/b/GoogleMLKit/3.2.0/GoogleMLKit.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_8_a_8.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/8/a/8/MapboxMaps/10.11.0-rc.1/MapboxMaps.podspec.json exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "MapboxMaps":
      In snapshot (Podfile.lock):
        MapboxMaps (= 10.9.1, ~> 10.9.0)

      In Podfile:
        mapbox_maps_flutter (from `.symlinks/plugins/mapbox_maps_flutter/ios`) was resolved to 0.4.1, which depends on
          MapboxMaps (~> 10.10.0)


    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * changed the constraints of dependency `MapboxMaps` inside your development pod `mapbox_maps_flutter`.
       You should run `pod update MapboxMaps` to apply changes you've made.

    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    <internal:kernel>:90:in `tap'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/bin/pod:25:in `load'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/bin/pod:25:in `<main>'

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update



Error running pod install
```

Is it a problem with cocoa pods in master?

**Comment by LjubiTech-Maxko** [comment] 2023-02-09 12:03
@AAverin1994 have you tried running `flutter clean` before building app? Or run the suggested `pod repo update`? I can only guess because I don't have iPhone to test it.

**Comment by AAverin1994** [comment] 2023-02-09 12:57
I've tried `flutter clean`, removed Pods directory and call `flutter build ios` again and got the same issue. I thought It should work without` pod repo update`.

**Comment by yunikkk** [comment] 2023-02-09 16:10
@AAverin1994 podfile.lock was not updated when the maps dependency was bumped to 10.10.0, however it is now, you can try once again, should work in the current main. 

Also, issues with multiple maps should be resolved by now. The 0.4.1 version including all these fixes is going to be published on pub.dev soon.

**Comment by AAverin1994** [comment] 2023-02-09 17:26
@yunikkk thank you for your answer. Yes, I have already solved my problem with cocoapods and checked getSource function again in version 0.4.1. It works for me.

**Closed** 2023-02-20 15:21 UTC
